name: my_portfolio
description: Serdun Dmitro
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  domain:
    path: ./package/domain

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  flex_color_scheme: ^7.3.1
  google_fonts: ^5.1.0
  go_router: ^10.1.2
  responsive_framework: ^1.1.0
  octo_image: ^1.0.2
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/language/uk.webp
    - assets/image/language/en.webp
    - assets/image/icons/category.webp
    - assets/image/icons/up_arrow.webp
    - assets/image/icons/sub_category.webp
    - assets/image/icons/google_play.webp
    - assets/image/icons/app_store.webp
