name: my_portfolio
description: Serdun Dmitro
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ^3.7.10

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  domain:
    path: package/domain

  data:
    path: package/data

  responsive_framework: ^0.1.7
  matrix4_transform: ^2.0.1
  octo_image: ^1.0.1
  url_launcher: ^6.1.0
  carousel_slider: ^4.1.1
  transparent_image: ^2.0.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.5.0
  flutter_bloc: ^8.0.1
  easy_localization: ^3.0.0
  logger: ^1.1.0
  go_router: ^8.0.5
  flex_color_scheme: ^7.1.2
  google_fonts: ^5.0.0



dev_dependencies:
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  injectable_generator: ^2.1.6
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/icons/facebook.webp
    - assets/image/icons/mail.webp
    - assets/image/icons/instagram.webp
    - assets/image/icons/linkedin.webp
    - assets/image/language/uk.webp
    - assets/image/language/en.webp
    - assets/image/icons/category.webp
    - assets/image/icons/up_arrow.webp
    - assets/image/icons/sub_category.webp
    - assets/image/icons/github.webp
    - assets/image/icons/phone.webp
    - assets/image/icons/google_play.webp
    - assets/image/icons/app_store.webp
    - assets/image/icons/location.webp
    - assets/translations/







