export const TYPES = {
    Applications: Symbol.for('Application'),
    FirestoreDatasource: Symbol.for('FirestoreDatasource'),
    StaticRepository: Symbol.for('StaticRepository'),
    ApplicationRepository: Symbol.for('ApplicationRepository'),
    ContactsRepository: Symbol.for('ContactsRepository'),
    ThemeRepository: Symbol.for('ThemeRepository'),
    ApplicationsService: Symbol.for('ApplicationsService'),
    ContactsService: Symbol.for('ContactsService'),
    AuthService: Symbol.for('AuthService'),
    StaticService: Symbol.for('StaticService'),
    StaticController: Symbol.for('StaticController'),
    ThemeService: Symbol.for('ThemeService'),
    ApplicationController: Symbol.for('ApplicationController'),
    ContactsController: Symbol.for('ContactsController'),
    ThemeController: Symbol.for('ThemeController'),
    AuthTrigger: Symbol.for('AuthTrigger'),
    ApplicationTrigger: Symbol.for('ApplicationTrigger'),
    ExceptionFilter: Symbol.for('ExceptionFilter'),
    // Mapper
    FirestoreApplicationMapper: Symbol.for('FirestoreApplicationMapper'),
    FirestoreContactMapper: Symbol.for('FirestoreContactMapper'),
    FirestoreThemeMapper: Symbol.for('FirestoreThemeMapper'),
}
